# -*- coding: utf-8 -*-
"""PitBit Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxNTJro_BIpc2faVTMAcWVmTfEhPpNFG
"""

# Import necessary libraries
import json
import re
from google.colab import files
from PyPDF2 import PdfReader

def parse_resume(resume_text):
    # Define regex patterns for different sections
    contact_info_pattern = r"Ph:.*\nEmail:.*\nLinkedIn:.*\n"
    summary_pattern = r"BRIEF SUMMARY.*\n(.*?)(?=\n[A-Z])"
    education_pattern = r"EDUCATION.*\n(.*?)(?=\n[A-Z])"
    experience_pattern = r"INTERNSHIPS.*\n(.*?)(?=\n[A-Z])"
    projects_pattern = r"PROJECTS.*\n(.*?)(?=\n[A-Z])"
    skills_pattern = r"Machine Learning.*\n(.*?)(?=\n[A-Z])"

    # Extract different sections
    contact_info = re.search(contact_info_pattern, resume_text, re.DOTALL)
    summary = re.search(summary_pattern, resume_text, re.DOTALL)
    education = re.search(education_pattern, resume_text, re.DOTALL)
    experience = re.search(experience_pattern, resume_text, re.DOTALL)
    projects = re.search(projects_pattern, resume_text, re.DOTALL)
    skills = re.search(skills_pattern, resume_text, re.DOTALL)

    # Process contact information
    contact_info_dict = {}
    if contact_info:
        contact_info_text = contact_info.group(0)
        contact_info_dict = {
            "Phone": re.search(r'Ph:\s*(.*)', contact_info_text).group(1),
            "Email": re.search(r'Email:\s*(.*)', contact_info_text).group(1),
            "LinkedIn": re.search(r'LinkedIn:\s*(.*)', contact_info_text).group(1)
        }

    # Process sections
    def extract_section(section):
        if section:
            return section.group(1).strip()
        return ""

    summary_text = extract_section(summary)
    education_text = extract_section(education)
    experience_text = extract_section(experience)
    projects_text = extract_section(projects)
    skills_text = extract_section(skills)

    # Convert extracted text into structured data
    resume_data = {
        "Contact Information": contact_info_dict,
        "Summary": summary_text,
        "Education": education_text,
        "Experience": experience_text,
        "Projects": projects_text,
        "Skills": skills_text
    }

    return resume_data

def read_pdf(file_path):
    reader = PdfReader(file_path)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

# Upload file
uploaded = files.upload()

# Assuming only one file is uploaded
for file_name in uploaded.keys():
    resume_text = read_pdf(file_name)
    resume_data = parse_resume(resume_text)
    resume_json = json.dumps(resume_data, indent=4)
    print(resume_json)

    # Save to a file
    with open('parsed_resume.json', 'w') as json_file:
        json_file.write(resume_json)

